apiVersion: openinfradev.github.com/v1
kind: HelmValuesTransformer
metadata:
  name: image
global:
  registry: private-registry:5000

charts:
- name: istio-operator
  override:
    hub: $(registry)/istio
    tag: 1.10.2

- name: jaeger-operator
  override:
    image.repository: $(registry)jaegertracing/jaeger-operator
    image.tag: 1.21.2

- name: kiali-operator
  override:
    image.repo: $(registry)/kiali/kiali-operator
    image.tag: v1.34.0

- name: servicemesh-controlplane
  override: {}

- name: servicemesh-gateway
  override: {}

- name: jaeger-operator
  override: {}

- name: servicemesh-jaeger-resource
  override: {}

- name: kiali-operator
  override: {}

- name: servicemesh-kiali-resource
  override: {}

- name: servicemesh-grafana-dashboard
  override: {}

- name: servicemesh-prometheusmonitor
  override: {}

- name: servicemesh-prometheusrule
  override: {}
