apiVersion: openinfradev.github.com/v1
kind: HelmValuesTransformer
metadata:
  name: site

global:
  awsMachineType: t3.large

charts:
- name: cluster-api-aws
  override:
    sshKeyName: taco
    cluster:
      name: hanu-reference
      region: ap-south-2
      networkSpec:
        ################################################################################
        ## vpc is a vpc-id of the VPC this provider should use to create resources. 
        ## it must set to an actual value.
        ################################################################################
        vpc: vpc-0559b909b56157f3a
    kubernetesVersion: v1.18.16
    kubeadmControlPlane.controlPlaneMachineType: $(awsMachineType)
    kubeadmControlPlane.rootVolume.size: 16
    machinePool.replicas: 2
    machinePool.machineType: $(awsMachineType)
    machinePool.rootVolume.size: 16
    ################################################################################
    ## machinePool.subnets is an array of subnet configurations in VPC.
    ## cluster api controller deploy machines in multi AZ based on provided subnets.
    ## it must set to an actual value.
    ################################################################################
    machinePool.subnets:
    - id: subnet-08b0c376db6d22893
    - id: subnet-06cfd42c5bfc5701f