apiVersion: openinfradev.github.com/v1
kind: HelmValuesTransformer
metadata:
  name: site

global:
  # These values are replaced on cluster creation by workflow
  clusterName: cluster.local
  sshKeyName: CHANGEME
  clusterRegion: CHANGEME
  cloudAccountID: CHANGEME

  tksCpNode: CHNAGEME
  tksCpNodeMax: CHANGEME
  tksCpNodeType: CHANGEME
  tksInfraNode: CHNAGEME
  tksInfraNodeMax: CHANGEME
  tksInfraNodeType: CHANGEME
  tksUserNode: CHANGEME
  tksUserNodeMax: CHANGEME
  tksUserNodeType: CHANGEME
  # 노드 스탑을 위해서는 min은 항상 0
  # 승규님 의견 추가: machine pool 노드에 축소불가설정 필요

charts:
- name: cluster-api-aws
  override:
    sshKeyName: $(sshKeyName)
    cluster:
      name: $(clusterName)
      region: $(clusterRegion)
      eksEnabled: true
      kubernetesVersion: v1.25.9
      eksAddons:
      - name: "aws-ebs-csi-driver"
        version: "v1.18.0-eksbuild.1"
        conflictResolution: "overwrite"
      - name: "vpc-cni"
        conflictResolution: "overwrite"
        version: "v1.12.6-eksbuild.2"
      multitenancyId:
        kind: AWSClusterRoleIdentity
        name: $(cloudAccountID)-account-role
      bastion:
        enabled: false
    machinePool:
    - name: taco
      machineType: $(tksInfraNodeType)
      replicas: $(tksInfraNode)
      minSize: $(tksInfraNode)
      maxSize: $(tksInfraNodeMax)
      rootVolume:
        size: 200
        type: gp2
      labels:
        taco-lma: enabled
        servicemesh: enabled
        taco-ingress-gateway: enabled
      roleAdditionalPolicies:
      - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
      - "arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy"
    - name: normal
      machineType: $(tksUserNodeType)
      replicas: $(tksUserNode)
      minSize: $(tksUserNode)
      maxSize: $(tksUserNodeMax)
      rootVolume:
        size: 50
        type: gp2
      roleAdditionalPolicies:
      - "arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy"

- name: ingress-nginx
  override:
    controller:
      nodeSelector:
        taco-lma: enabled
      service:
        externalTrafficPolicy: Local
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-name: "taco-ingress-nlb"
          service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
          service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
        type: LoadBalancer
      config:
        enable-underscores-in-headers: "true"
        proxy-body-size: "10m"

- name: cluster-autoscaler-rbac
  override:
    deployMgmtRbacOnly:
      targetNamespace: $(clusterName)

- name: cluster-autoscaler
  override:
    image:
      repository: harbor.taco-cat.xyz/tks/cluster-autoscaler
      tag: v1.25.3
    autoDiscovery:
      clusterName: $(clusterName)
    cloudProvider: aws
    awsRegion: ap-northeast-2
    rbac:
     serviceAccount:
       create: false
       name: "cluster-autoscaler"
    extraArgs:
      expander: priority
    expanderPriorities:
      "10":
        - .*-taco
      "50":
        - .*-normal
