apiVersion: openinfradev.github.com/v1
kind: HelmValuesTransformer
metadata:
  name: image
global:
  registry: ${LOCAL_REGISTRY}:5000

charts:
- name: eck-resource
  override:
    elasticsearch.image.repository: $(registry)/elasticsearch/elasticsearch
    elasticsearch.image.tag: 7.5.1
    kibana.image.repository: $(registry)/kibana/kibana
    kibana.image.tag: 7.5.1

- name: eck-operator
  override:
    image.repository: $(registry)/eck/eck-operator
    image.tag: 1.6.0

- name: addons
  override:
    kibanaInit.image.repository: $(registry)/sktdev/kibana-init
    kibanaInit.image.tag: v4
    metricbeat.image.repository: $(registry)/metricbeat
    metricbeat.image.tag: taco-1.0.0
    tacoWatcher.joinCluster.image.repository: $(registry)/curl
    tacoWatcher.joinCluster.image.tag: latest

- name: fluentbit
  override:
    image.exporter.repository: $(registry)/siim/logalert-exporter
    image.exporter.tag: v0.1.1
    image.fluentbit.repository: $(registry)/openinfradev/fluentbit
    image.fluentbit.tag: v1.9.9
    image.elasticsearchTemplates.repository: $(registry)/openstackhelm/heat
    image.elasticsearchTemplates.tag: newton

- name: fluent-operator
  override:
    operator.initcontainer.repository: "$(registry)/docker"
    operator.initcontainer.tag: "19.03"
    operator.container.repository: "$(registry)/kubesphere/fluent-operator"
    operator.container.tag: "v1.5.1"
    fluentbit.image.repository: "$(registry)/kubesphere/fluent-bit"
    fluentbit.image.tag: "v1.9.9"

- name: grafana
  override:
    downloadDashboardsImage.repository: $(registry)/curl
    downloadDashboardsImage.tag: 7.70.0
    image.repository: $(registry)/grafana/grafana
    image.tag: 7.1.1
    initChownData.image.repository: $(registry)/library/busybox
    initChownData.image.tag: 1.31.1
    sidecar.image.repository: $(registry)/kiwigrid/k8s-sidecar
    sidecar.image.tag: 0.1.151
    testFramework.image: $(registry)/bats
    testFramework.tag: v1.1.0

- name: kube-state-metrics
  override:
    global.imageRegistry: $(registry)
    image.repository: bitnami/kube-state-metrics
    image.tag: 1.9.7-debian-10-r143

- name: prometheus
  override:
    alertmanager.alertmanagerSpec.image.repository: $(registry)/prometheus/alertmanager
    alertmanager.alertmanagerSpec.image.tag: v0.21.0
    prometheusOperator.admissionWebhooks.patch.image.repository: $(registry)/jettech/kube-webhook-certgen
    prometheusOperator.admissionWebhooks.patch.image.tag: v1.5.0
    prometheusOperator.image.repository: $(registry)/prometheus-operator/prometheus-operator
    prometheusOperator.image.tag: v0.46.0
    prometheusOperator.prometheusConfigReloaderImage.repository: $(registry)/prometheus-operator/prometheus-config-reloader
    prometheusOperator.prometheusConfigReloaderImage.tag: v0.46.0
    prometheus.prometheusSpec.image.repository: $(registry)/prometheus/prometheus
    prometheus.prometheusSpec.image.tag: v2.24.0

- name: prometheus-adapter
  override:
    image.repository: $(registry)/directxman12/k8s-prometheus-adapter-amd64
    image.tag: v0.7.0

- name: prometheus-node-exporter
  override:
    image.repository: $(registry)/prometheus/node-exporter
    image.tag: v1.0.1

- name: prometheus-operator
  override:
    alertmanager.alertmanagerSpec.image.repository: $(registry)/prometheus/alertmanager
    alertmanager.alertmanagerSpec.image.tag: v0.21.0
    prometheusOperator.admissionWebhooks.patch.image.repository: $(registry)/jettech/kube-webhook-certgen
    prometheusOperator.admissionWebhooks.patch.image.tag: v1.5.0
    prometheusOperator.image.repository: $(registry)/prometheus-operator/prometheus-operator
    prometheusOperator.image.tag: v0.46.0
    prometheusOperator.prometheusConfigReloaderImage.repository: $(registry)/prometheus-operator/prometheus-config-reloader
    prometheusOperator.prometheusConfigReloaderImage.tag: v0.46.0
    prometheus.prometheusSpec.image.repository: $(registry)/prometheus/prometheus
    prometheus.prometheusSpec.image.tag: v2.24.0

- name: prometheus-process-exporter
  override:
    images.tags.dep_check: $(registry)/airshipit/kubernetes-entrypoint:v1.0.0
    images.tags.image_repo_sync: $(registry)/library/docker:17.07.0
    images.tags.process_exporter: $(registry)/ncabatoff/process-exporter:0.2.11

- name: prometheus-pushgateway
  override:
    image.repository: $(registry)/prom/pushgateway
    image.tag: v1.3.0

- name: kubernetes-event-exporter
  override:
    image.repository: $(registry)/siim/kubernetes-event-exporter
    image.tag: 0.1.0
    image.PullPolicy: IfNotPresent

- name: thanos
  override:
    image.registry: $(registry)
    image.repository: bitnami/thanos
    image.tag: 0.17.2-scratch-r1
    volumePermissions.image.registry: $(registry)
    volumePermissions.image.repository: bitnami/minideb
    volumePermissions.image.tag: buster
    minio.image.registry: $(registry)
    minio.image.repository: bitnami/minio
    minio.image.tag: 2021.2.14-debian-10-r0
    minio.clientImage.registry: $(registry)
    minio.clientImage.repository: bitnami/minio-client
    minio.clientImage.tag: 2021.2.14-debian-10-r0
    minio.volumePermissions.image.registry: $(registry)
    minio.volumePermissions.image.repository: bitnami/minideb
    minio.volumePermissions.image.tag: buster

- name: thanos-config
  override: {}

- name: prepare-etcd-secret
  override:
    image.repository: $(registry)/hyperkube
